### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by LYoung520** [IvanEvan/voiceProfile-for-gender-age-classify#1]
I have tested the pre-trained model. The performance of it was impressive. Now I want to train my own model. I read 'runme.sh' and it seems that we don't need any label of our dataset. Am I right? In other words, is it an unsupervised process?

It would be appreciate if you can give me any clue about the training process such as a paper or something like that.

Thanks a lot!

**Comment by IvanEvan** [comment]
> I have tested the pre-trained model. The performance of it was impressive. Now I want to train my own model. I read 'runme.sh' and it seems that we don't need any label of our dataset. Am I right? In other words, is it an unsupervised process?
> 
> It would be appreciate if you can give me any clue about the training process such as a paper or something like that.
> 
> Thanks a lot!

Sorry for a late answer!

I upload this repo after my last internship.And busy with graduation so not notice your question.

I believe you have solved the problem by reading the code carefully.But I still help you out.

This is of course supervised learning.You need prepare your data folder like this:
---------data
&emsp;&emsp; |----------train
&emsp;&emsp;|----------test
and each wav data end with its label like this:
for age:
&emsp;&emsp;123445_child.wav
&emsp;&emsp;25468_adult.wav
&emsp;&emsp;84652_child.wav
&emsp;&emsp;......
